name: Android CI - Dev

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - run: chmod +x ./gradlew

      - run: ./gradlew assembleDevRelease

      - uses: actions/upload-artifact@v4
        with:
          name: dev-apk
          path: app/build/outputs/apk/dev/release/*.apk

