name: Android CI - Prod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - run: chmod +x ./gradlew

      - run: ./gradlew assembleProdRelease

      - uses: actions/upload-artifact@v4
        with:
          name: prod-apk
          path: app/build/outputs/apk/prod/release/*.apk

