name: Android CI - Prod Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - run: chmod +x ./gradlew

      # ✅ Extract versionName
      - name: Extract versionName
        id: version
        run: |
          VERSION_NAME=$(grep versionName app/build.gradle | head -1 | awk -F'"' '{ print $2 }')
          echo "VERSION_NAME=$VERSION_NAME"
          echo "version_name=$VERSION_NAME" >> $GITHUB_OUTPUT

      # ✅ Calculate versionCode as commit count
      - name: Generate versionCode
        id: versioncode
        run: |
          VERSION_CODE=$(git rev-list --count HEAD)
          echo "VERSION_CODE=$VERSION_CODE"
          echo "version_code=$VERSION_CODE" >> $GITHUB_OUTPUT

      # ✅ Build the prod APK using injected versionCode
      - name: Build APK
        run: ./gradlew assembleProdRelease -PVERSION_CODE=${{ steps.versioncode.outputs.version_code }}

      # ✅ Create Git tag like v1.1
      - name: Tag & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag v${{ steps.version.outputs.version_name }} || true
          git push origin v${{ steps.version.outputs.version_name }} || true

      # ✅ Create GitHub Release and upload APK
      - name: GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version_name }}
          name: "Release v${{ steps.version.outputs.version_name }}"
          files: app/build/outputs/apk/prod/release/*.apk

