name: Android CI - Stage Release

on:
  push:
    branches:
      - stage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - run: chmod +x ./gradlew

      - name: Bump versionName
        id: version_bump
        run: |
          FILE=app/build.gradle
          CURRENT_VERSION=$(grep versionName $FILE | head -1 | awk -F\" '{ print $2 }')
          MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
          MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
          NEW_VERSION="$MAJOR.$((MINOR + 1))"
          sed -i "s/versionName \"$CURRENT_VERSION\"/versionName \"$NEW_VERSION\"/" $FILE
          echo "version_name=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit version bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add app/build.gradle
          git commit -m "🔖 Bump versionName to ${{ steps.version_bump.outputs.version_name }}"
          git push origin stage

      - name: Generate versionCode
        id: versioncode
        run: |
          VERSION_CODE=$(git rev-list --count HEAD)
          echo "version_code=$VERSION_CODE" >> $GITHUB_OUTPUT

      - name: Build APK
        run: ./gradlew assembleStageRelease -PVERSION_CODE=${{ steps.versioncode.outputs.version_code }}

      - name: Tag & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag v${{ steps.version_bump.outputs.version_name }}-stage || true
          git push origin v${{ steps.version_bump.outputs.version_name }}-stage || true

      - name: GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version_bump.outputs.version_name }}-stage
          name: "Stage Release v${{ steps.version_bump.outputs.version_name }}"
          files: app/build/outputs/apk/stage/release/*.apk

